my_string = input("Привет, больше не пиши сюда: ")
print(len('Привет, больше не пиши сюда: '))
print('my_string'.upper())
print('my_string'.lower())
print('Привет, больше не пиши сюда: '.replace(' ','#'))
print('my_string' [0])
print('my_string' [-1])
